server:
  port: 0

spring:
  application:
    name: shopping-store
  datasource:
    url: jdbc:postgresql://localhost:5432/commerce_shopping_store
    username: postgres
    password: changeme
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registryFetchIntervalSeconds: 5
    initialInstanceInfoReplicationIntervalSeconds: 5
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10

logging:
  level:
    ru.yandex.practicum.commerce: INFO
    org.springframework: WARN

management:
  endpoints:
    web:
      exposure:
        include: health,info